apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safesqlproxy.fullname" . }}
  labels:
    {{- include "safesqlproxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  DI_DSN: {{ .Values.warehouse.dsn | quote }}
